# Generated by Django 5.1.4 on 2026-09-07 06:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("STACKABLE", "Stackable")],
                        max_length=16,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("max_redemptions", models.PositiveIntegerField()),
                ("redeemed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "coupons",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("redeemed_count__lte", models.F("max_redemptions"))
                        ),
                        name="coupon_redeemed_within_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_redemptions__gte", 1)),
                        name="coupon_max_redemptions_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_percent__gt", 0), ("discount_percent__lte", 100)
                        ),
                        name="coupon_discount_percent_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("PLACED", "Placed"), ("CANCELLED", "Cancelled")],
                        default="PLACED",
                        max_length=16,
                    ),
                ),
                ("is_single_use", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="redemption.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="redemption.user",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", Decimal("0"))),
                        name="order_amount_non_negative",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_single_use", True), ("status", "PLACED")
                        ),
                        fields=("coupon", "user"),
                        name="uniq_standard_coupon_active_per_user",
                    ),
                ],
            },
        ),
    ]
